// Code generated by go-swagger; DO NOT EDIT.

// Package restapi company_info.proto
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: version not set
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
