// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: company_info.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CompanyInfoSearcherClient is the client API for CompanyInfoSearcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompanyInfoSearcherClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type companyInfoSearcherClient struct {
	cc grpc.ClientConnInterface
}

func NewCompanyInfoSearcherClient(cc grpc.ClientConnInterface) CompanyInfoSearcherClient {
	return &companyInfoSearcherClient{cc}
}

func (c *companyInfoSearcherClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/CompanyInfoSearcher/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompanyInfoSearcherServer is the server API for CompanyInfoSearcher service.
// All implementations must embed UnimplementedCompanyInfoSearcherServer
// for forward compatibility
type CompanyInfoSearcherServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedCompanyInfoSearcherServer()
}

// UnimplementedCompanyInfoSearcherServer must be embedded to have forward compatible implementations.
type UnimplementedCompanyInfoSearcherServer struct {
}

func (UnimplementedCompanyInfoSearcherServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedCompanyInfoSearcherServer) mustEmbedUnimplementedCompanyInfoSearcherServer() {}

// UnsafeCompanyInfoSearcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompanyInfoSearcherServer will
// result in compilation errors.
type UnsafeCompanyInfoSearcherServer interface {
	mustEmbedUnimplementedCompanyInfoSearcherServer()
}

func RegisterCompanyInfoSearcherServer(s grpc.ServiceRegistrar, srv CompanyInfoSearcherServer) {
	s.RegisterService(&CompanyInfoSearcher_ServiceDesc, srv)
}

func _CompanyInfoSearcher_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyInfoSearcherServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CompanyInfoSearcher/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyInfoSearcherServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompanyInfoSearcher_ServiceDesc is the grpc.ServiceDesc for CompanyInfoSearcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompanyInfoSearcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CompanyInfoSearcher",
	HandlerType: (*CompanyInfoSearcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _CompanyInfoSearcher_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "company_info.proto",
}
