// Code generated by go-swagger; DO NOT EDIT.

package company_info_searcher

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/danmory/company-info-service/internal/docs/models"
)

// CompanyInfoSearcherSearchOKCode is the HTTP code returned for type CompanyInfoSearcherSearchOK
const CompanyInfoSearcherSearchOKCode int = 200

/*
CompanyInfoSearcherSearchOK A successful response.

swagger:response companyInfoSearcherSearchOK
*/
type CompanyInfoSearcherSearchOK struct {

	/*
	  In: Body
	*/
	Payload *models.SearchResponse `json:"body,omitempty"`
}

// NewCompanyInfoSearcherSearchOK creates CompanyInfoSearcherSearchOK with default headers values
func NewCompanyInfoSearcherSearchOK() *CompanyInfoSearcherSearchOK {

	return &CompanyInfoSearcherSearchOK{}
}

// WithPayload adds the payload to the company info searcher search o k response
func (o *CompanyInfoSearcherSearchOK) WithPayload(payload *models.SearchResponse) *CompanyInfoSearcherSearchOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the company info searcher search o k response
func (o *CompanyInfoSearcherSearchOK) SetPayload(payload *models.SearchResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CompanyInfoSearcherSearchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
CompanyInfoSearcherSearchDefault An unexpected error response.

swagger:response companyInfoSearcherSearchDefault
*/
type CompanyInfoSearcherSearchDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.RuntimeError `json:"body,omitempty"`
}

// NewCompanyInfoSearcherSearchDefault creates CompanyInfoSearcherSearchDefault with default headers values
func NewCompanyInfoSearcherSearchDefault(code int) *CompanyInfoSearcherSearchDefault {
	if code <= 0 {
		code = 500
	}

	return &CompanyInfoSearcherSearchDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the company info searcher search default response
func (o *CompanyInfoSearcherSearchDefault) WithStatusCode(code int) *CompanyInfoSearcherSearchDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the company info searcher search default response
func (o *CompanyInfoSearcherSearchDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the company info searcher search default response
func (o *CompanyInfoSearcherSearchDefault) WithPayload(payload *models.RuntimeError) *CompanyInfoSearcherSearchDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the company info searcher search default response
func (o *CompanyInfoSearcherSearchDefault) SetPayload(payload *models.RuntimeError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CompanyInfoSearcherSearchDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
